name: Node and Docker

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      NAME:  # name of service, (ex: peeq-tracking)
        required: true
        type: string
      VERSION:
        required: true
        type: string
      NODE_VERSION:
        default: 18
        required: false
        type: number
      DOCKERFILE_FILE:
        default: './Dockerfile'
        required: false
        type: string
      TEST_CMD:
        default: 'npm test'
        required: false
        type: string
      REGISTRY_LOGIN_SERVER:
        default: 'jxshipmagic.azurecr.io'
        required: false
        type: string

    secrets:
      GH_TOKEN:  # GitHub token
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:

  node-docker:
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 Setup node.js"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: npm

      - name: "🔨 NPM install"
        run: npm install --legacy-peers-deps

      # - name: "🔨 NPM test"
      #   run: ${{ inputs.TEST_CMD }}

      - name: "🔨 NPM build"
        run: npm run build

# https://learn.microsoft.com/en-us/azure/container-instances/container-instances-github-action
      - name: '🐳 Docker login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: '🐳 Docker build, tag and push'
        run: |
          docker build -f ${{ inputs.DOCKERFILE_FILE }} -t ${{ inputs.NAME }} .
          docker image tag ${{ inputs.NAME }} "${{ inputs.REGISTRY_LOGIN_SERVER }}/shipmagic/${{ inputs.NAME }}:${{ inputs.VERSION }}"
          docker push -a "${{ inputs.REGISTRY_LOGIN_SERVER }}/shipmagic/${{ inputs.NAME }}"
